---
PreCommit:
  ALL:
    exclude:
      - 'test/dummy/**/*'

  RuboCop:
    enabled: true
#    on_warn: fail # Treat all warnings as failures

  BundleAudit:
    enabled: true

  RailsBestPractices:
    enabled: true

  YamlLint:
    enabled: true

  TrailingWhitespace:
    enabled: true
    exclude:
      - '**/db/structure.sql'
      - 'rdoc/**/*'

PostCheckout:
  ALL:
    quiet: true

#  IndexTags:
#    enabled: true   # Generate a tags file with `ctags` each time HEAD changes
