# frozen_string_literal: true

customize_gemfiles do
  {
    single_quotes: true,
    heading: <<~HEADING
      frozen_string_literal: true

      `%{gemfile}s` has been generated by Appraisal, do NOT modify it or `%{lockfile}s` directly!
      Make the changes to the "%{appraisal}s" block in `Appraisals` instead.
    HEADING
  }
end

appraise 'rails-5' do
  gem 'rails', '5.2.0'
  gem 'sqlite3'
end

appraise 'rails-6' do
  gem 'rails', '6.0.0'
  gem 'sqlite3'
end

appraise 'rails-7' do
  gem 'rails', '7.0.0'
  gem 'sqlite3'
end
