# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.4.0

pipelines:
  default:
    - step:
        caches:
          - bundler
        script:
          - ruby -v
          - bundle install
          - rake
  branches:
    live:
      - step:
          name: Push to ruby-gems.org
          deployment: production
          script:
            - ruby -v
            - bundle install
            - rake
            - rake rdoc
            - rm -f partial_menu-*.gem
            - gem build partial_menu
            - gem push partial_menu-*.gem
definitions:
  caches:
    bundler: ./vendor
