---
name: Publish Gem

on:
  push:
    branches:
      - "release"
    tags:
      - v*
jobs:
  push:
    name: Push gem to RubyGems.org
    environment: release
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      # Set up
      - uses: actions/checkout@main
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}

      # Release
      - uses: rubygems/release-gem@v1
